name: NextUI Node.js CI

on:
  push:
    branches: 
      - main 
  workflow_dispatch:

jobs:
  page-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v2 
      
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: "npm"
          
    - name: Install dependencies
      run: yarn install
      
    - name: Build project
      run: yarn build
      
    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
